export class Paciente { 
    id_paciente;
    nombre;
    ap_paterno;
    ap_materno;
    fecha_nac;
    sexo = "1";
    tel_fijo = "";
    tel_cel = "";
    tel_alter = "";
    email;
    RFC;
    calle;
    no_ext;
    no_int;
    id_edo;
    id_mun;
    ciudad;
    colonia;
    datos_fact = 1;
    tipo_sangre;
    alergias;
    cronicas;
    anotacion;
    fact_persona = "1";
    fact_razonsoc;
    fact_rfc;
    fact_cp = "";
    fact_calle;
    fact_ext;
    fact_int;
    fact_idedo;
    fact_idmun;
    fact_colonia;
    fact_email;
}